spring:
   profiles:
   active: -dev

---
spring:
   profiles: dev    #开发环境
   application: 
      name: microservicecloud-config-client
server:
    port: 8201
eureka:
   client:
      service-url:
         defaultZone: http://eureka-dev:7001/eureka/

---
spring:
   profiles: test    #测试环境
   application: 
      name: microservicecloud-config-client
server:
    port: 8202
eureka:
   client:
      service-url:
         defaultZone: http://eureka-test:7001/eureka/